### ISSUE TITLE
Out of memory, infinite loop possible?

### ISSUE THREAD

**Issue by mtinnes** [antoinerg/elementary-circuits-directed-graph#9]
We experience a run away memory issue on occasion in which the circuits variable seems to grow indefinitely. The following edges trigger the issue:

[[9,13,6,2,4,0,12,11,7,15,10,5,14,3],[15,9,2,14,6,5,0,7,4],[15,13,5,4,6,3,2,0,14,11,7],[10,3,13,2,15,9,8,5,7,4,0,14,6,11,12],[3,10,4,7,14,15,6,12,0],[10,15,0,6,3,7,13,9,5,2,14],[6,3,9,0,4,7,2,15,5,14,10],[6,11,4,7,13,14,0,2,5,3,10,15,8,12],[7,8,15,9,14,0],[9,11,10,7,5,3,6,0,14,15],[7,0,10,6,3,5,9,4,14,15,2],[11,3,9,8,14,2,7,0,5,15,4],[4,12,15,14,10,0,7,3],[2,5,14,15,13,0,3,7],[2,10,7,0,3,6,14,5,4,15,11,9],[15,14,6,2,5,7,0]]

Is something to be resolved in the algorithm, or the data itself?

Sample code:
```
var findCircuits = require("elementary-circuits-directed-graph");

var adjacencyList = [
  [9,13,6,2,4,0,12,11,7,15,10,5,14,3],
  [15,9,2,14,6,5,0,7,4],
  [15,13,5,4,6,3,2,0,14,11,7],
  [10,3,13,2,15,9,8,5,7,4,0,14,6,11,12],
  [3,10,4,7,14,15,6,12,0],
  [10,15,0,6,3,7,13,9,5,2,14],
  [6,3,9,0,4,7,2,15,5,14,10],
  [6,11,4,7,13,14,0,2,5,3,10,15,8,12],
  [7,8,15,9,14,0],
  [9,11,10,7,5,3,6,0,14,15],
  [7,0,10,6,3,5,9,4,14,15,2],
  [11,3,9,8,14,2,7,0,5,15,4],
  [4,12,15,14,10,0,7,3],
  [2,5,14,15,13,0,3,7],
  [2,10,7,0,3,6,14,5,4,15,11,9],
  [15,14,6,2,5,7,0]
]

console.log(findCircuits(adjacencyList))
```

**Comment by antoinerg** [comment]
Thank you @mtinnes for reporting this issue! 

I will have a look later. My guess is that there's nothing wrong with the data: it's probably a problem with the implementation.

**Comment by mtinnes** [comment]
Some more info - seems to get stuck in `circuit()` on the first iteration when `leastVertex = 0` in this section of code:

```
        // L1
        var i;
        var w;
        for(i = 0; i < Ak[v].length; i++) {
            w = Ak[v][i];
            if(w === s) {
                output(s, stack);
                found = true;
            } else if(!blocked[w]) {
                found = circuit(w); 
            }
        }
```
It's infinitely adding to `output()` when `w === s` which are `0`

Ak:
```
[
[9,13,6,2,4,0,12,11,7,15,10,5,14,3],
[],
[15,13,5,4,6,3,2,0,14,11,7],
[10,3,13,2,15,9,8,5,7,4,0,14,6,11,12],
[3,10,4,7,14,15,6,12,0],
[10,15,0,6,3,7,13,9,5,2,14],
[6,3,9,0,4,7,2,15,5,14,10],
[6,11,4,7,13,14,0,2,5,3,10,15,8,12],
[7,8,15,9,14,0],
[9,11,10,7,5,3,6,0,14,15],
[7,0,10,6,3,5,9,4,14,15,2],
[11,3,9,8,14,2,7,0,5,15,4],
[4,12,15,14,10,0,7,3],
[2,5,14,15,13,0,3,7],
[2,10,7,0,3,6,14,5,4,15,11,9],
[15,14,6,2,5,7,0]
]
```

**Comment by antoinerg** [comment]
@mtinnes FYI I noticed that some of your nodes are linking to themselves. I removed those "self-links" but the problem didn't disappear. Still investigating :male_detective:

**Comment by antoinerg** [comment]
Your graph looks like this:
![graph](https://user-images.githubusercontent.com/301546/74063266-14cfd480-49be-11ea-9455-486adacc4427.png)

**Comment by antoinerg** [comment]
@mtinnes I'm starting to wonder whether we're reaching an out of memory condition because there are just too many elementary circuits. 

In a complete directed graph with `n` nodes, there are:
```python
import numpy as np
import scipy.special
n=15
i=np.arange(0,n)
sum(scipy.special.binom(n, n - i -1) * scipy.special.factorial(n-i))
```
32396622193141 circuits so rougly 32E12. Way more than we could hope writing in memory. 

Now I understand your graph is not fully connected but it does contain a lot of links. In the `output` function, instead of pushing newly found circuits to an array in memory, I instead write them to a file. The file quickly grew to several hundreds of megabytes and it already found more than ten millions of elementary circuits in your graph!

I think we should allow the user to provide its own callback function to be fired each time an elementary circuit is found. Keeping them all in memory is not realistic in many cases.

**Comment by antoinerg** [comment]
@mtinnes actually it found 34042143 circuits. It would be nice to compare this number with another implementation of the algorithm to see if it's the same.

**Comment by mtinnes** [comment]
Thanks for the help, your code is found in this project for identifying cycles, which is what I'm actually trying use:
https://github.com/tomshanley/d3-sankey-circular

Do you think there is another more efficient method for this?

Here is the portion of code using your library in the sankey library:
```
  /// /////////////////////////////////////////////////////////////////////////////////
  // Cycle functions
  // portion of code to detect circular links based on Colin Fergus' bl.ock https://gist.github.com/cfergus/3956043

  // Identify circles in the link objects
  function identifyCircles(graph, id, sortNodes) {
    var circularLinkID = 0;
    if (sortNodes === null) {

      // Building adjacency graph
      var adjList = [];
      for (var i = 0; i < graph.links.length; i++) {
        var link = graph.links[i];
        var source = link.source.index;
        var target = link.target.index;
        if (!adjList[source]) adjList[source] = [];
        if (!adjList[target]) adjList[target] = [];

        // Add links if not already in set
        if (adjList[source].indexOf(target) === -1) adjList[source].push(target);
      }

      // Find all elementary circuits
      var cycles = findCircuits(adjList);

      // Sort by circuits length
      cycles.sort(function (a, b) {
        return a.length - b.length;
      });

      var circularLinks = {};
      for (i = 0; i < cycles.length; i++) {
        var cycle = cycles[i];
        var last = cycle.slice(-2);
        if (!circularLinks[last[0]]) circularLinks[last[0]] = {};
        circularLinks[last[0]][last[1]] = true;
      }

      graph.links.forEach(function (link) {
        var target = link.target.index;
        var source = link.source.index;
        // If self-linking or a back-edge
        if (target === source || circularLinks[source] && circularLinks[source][target]) {
          link.circular = true;
          link.circularLinkID = circularLinkID;
          circularLinkID = circularLinkID + 1;
        } else {
          link.circular = false;
        }
      });
    } else {
      graph.links.forEach(function (link) {
        if (link.source[sortNodes] < link.target[sortNodes]) {
          link.circular = false;
        } else {
          link.circular = true;
          link.circularLinkID = circularLinkID;
          circularLinkID = circularLinkID + 1;
        }
      });
    }
  }
```

**Comment by antoinerg** [comment]
I understand your use case better @mtinnes ... 

I think it will be challenging to represent your graph using a Sankey diagram because there are a lot of circular links. I don't think `d3-sankey-circular` will do a good job in those situations. That being said, there might be a better way to do things. 

In `d3-sankey-circular`, there are two types of links: regular ones (drawn like the ones from `d3-sankey`) and circular ones (which loop and go backward). The challenge is determining the type of each link in a given graph. The way I did it in `d3-sankey-circular` was to find all the elementary circuits and flags the second to last link as the one which is circular. This approach is, of course, problematic when there are tens of millions of elementary circuits as you encountered :disappointed: . Please let us know over at `d3-sankey-circular` if you think of a better way to do this task!

Thanks for your time @mtinnes
